version: '3.8'

services:
  app:
    build: .
    container_name: poloniex-collector
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=poloniex
      - DATABASE_SSLMODE=disable
    volumes:
      - ./config:/app/config
    restart: unless-stopped

  postgres:
    image: postgres:14-alpine
    container_name: poloniex-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=poloniex
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: